i18n for new Accounts section
reactioncommerce/api-service-account pull request #14
Opened 2020-05-02 22:29 UTC by loan-laux

Signed-off-by: Loan Laux <loan@outgrow.io>

Impact: **major**
Type: **chore**

i18n to go with the new Accounts section at [reaction-admin#276](https://github.com/reactioncommerce/reaction-admin/pull/276).

2020-05-07 12:32 UTC, aldeed requested changes
The new stuff looks fine but we can't remove any existing translations since you don't know what version of admin they will be connecting with.

2020-05-08 13:27 UTC, loan-laux commented
@aldeed Thanks! Indeed, I hadn't thought about backwards compatibility. Thanks for the reminder.

I've added the old strings back, as well as the new strings for the Invitations page.

2020-05-11 22:22 UTC, aldeed approved these changes

2020-05-11 22:22 UTC, merged

2020-05-11 22:24 UTC, rc-publisher commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@reactioncommerce/api-plugin-accounts/v/1.3.0)
- [GitHub release](https://github.com/reactioncommerce/api-plugin-accounts/releases/tag/v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: